import { createClientWithScope } from "./internal.js";
import type { ClientResolvers } from "./internal.js";

export type {
  ActorId,
  ActivityId,
  AfferentActionResult,
  AfferentErrorDto,
  AdminCapabilities,
  AdminChangelogEntryDto,
  BoardDto,
  BoardId,
  CommentDto,
  CommentId,
  CommentPageDto,
  ChangelogId,
  ChangelogLinkedPostDto,
  ChangelogPageDto,
  NotificationCapabilities,
  NotificationDto,
  NotificationEventType,
  NotificationId,
  NotificationPageDto,
  PostSubscriptionDto,
  UnreadNotificationCountDto,
  DiscoveryPostDto,
  FeedbackOrder,
  FeedbackPageDto,
  FeedbackPostDto,
  ParticipationCapabilities,
  PaginationOptions,
  PostCountDto,
  PostDto,
  PostPageDto,
  PostId,
  PostActivityDto,
  PostActivityPageDto,
  PublicChangelogEntryDto,
  PublishedChangelogLookupDto,
  PostStatusKey,
  ReadCapabilities,
  RoadmapGroupPageDto,
  RoadmapItemDto,
  RoadmapStatusKey,
  SearchResultDto,
  SimilarPostResultDto,
  TagDeleteResultDto,
  TagDto,
  TagId,
  TagListDto,
  VerifiedActor,
} from "./contracts.js";
export {
  addCommentIntentValidator,
  adminEditPostIntentValidator,
  adminChangelogEntryResultValidator,
  anonymizeActorIntentValidator,
  boardListResultValidator,
  changelogLinkedPostResultValidator,
  changelogPageResultValidator,
  commentPageResultValidator,
  configureInstallationIntentValidator,
  createChangelogDraftIntentValidator,
  createTagIntentValidator,
  countPostsIntentValidator,
  countResultValidator,
  deleteTagIntentValidator,
  createPostIntentValidator,
  discoveryPostResultValidator,
  editPostIntentValidator,
  editChangelogIntentValidator,
  getPostIntentValidator,
  getPostSubscriptionIntentValidator,
  getUnreadNotificationCountIntentValidator,
  getPublishedChangelogBySlugIntentValidator,
  installationResultValidator,
  listBoardsIntentValidator,
  listCommentsIntentValidator,
  listPostActivityIntentValidator,
  listPublishedChangelogIntentValidator,
  listRoadmapGroupIntentValidator,
  listTagsIntentValidator,
  listFeedbackIntentValidator,
  listPostsIntentValidator,
  listNotificationsIntentValidator,
  postListResultValidator,
  postPageResultValidator,
  feedbackPageResultValidator,
  publicFeedbackPostDtoValidator,
  publicChangelogEntryResultValidator,
  publicAfferentErrorValidator,
  publicParticipationFailureValidator,
  publicPostActionResultValidator,
  publicCommentActionResultValidator,
  publicPostDtoValidator,
  publishChangelogIntentValidator,
  publishedChangelogLookupResultValidator,
  roadmapGroupPageResultValidator,
  roadmapItemResultValidator,
  publicCommentDtoValidator,
  notificationPageResultValidator,
  notificationResultValidator,
  postSubscriptionResultValidator,
  unreadNotificationCountResultValidator,
  searchFeedbackIntentValidator,
  searchFeedbackResultValidator,
  setVoteIntentValidator,
  setPostSubscriptionIntentValidator,
  setArchivedIntentValidator,
  setDiscussionLockIntentValidator,
  setPostTagIntentValidator,
  setPostStatusIntentValidator,
  setChangelogLinksIntentValidator,
  movePostIntentValidator,
  renameTagIntentValidator,
  similarPostResultValidator,
  suggestSimilarPostsIntentValidator,
  tagDeleteResultValidator,
  tagListResultValidator,
  tagResultValidator,
  withdrawPostIntentValidator,
  unpublishChangelogIntentValidator,
  markNotificationReadIntentValidator,
} from "./contracts.js";

const FIXED_SCOPE = "afferent:single-product:v1";

export type AfferentClientOptions = Omit<ClientResolvers, "resolveScope">;

export type { AfferentClient } from "./internal.js";

export function createAfferentClient(
  component: Parameters<typeof createClientWithScope>[0],
  options: AfferentClientOptions,
): ReturnType<typeof createClientWithScope> {
  return createClientWithScope(component, {
    ...options,
    resolveScope: async () => FIXED_SCOPE,
  });
}

export { createScopedAfferentClient } from "./server.js";
export type { ScopedAfferentClientOptions } from "./server.js";
